### PR TITLE
add endpoints required by filebeat

### PR DESCRIPTION
**Pull request by jrwren**

### CODE REVIEW

**Comment by jrwren** [comment]
This is a WIP PR. I am trying to get filebeat to work and I see it looks for simple things, but then it tries to upload templates and I'm not sure what I should do with those.

Does anyone have any advice RE the template endpoint? Just store by name and on GET return what was send in PUT?

**Comment by jrwren** [comment]
for #25

**Comment by hengfeiyang** [comment]
thanks for your pr, we are now support filebeat, that is base on compatible es apis.

https://github.com/prabhatsharma/zinc/pull/90

**Comment by jrwren** [comment]
Thanks.

**Pull request closed without merging**
